### ISSUE TITLE
No data feature implementation

### ISSUE THREAD

**Issue by rcavaliere** [tis-innovation-park/cleanroads-map#1]
When for some technical reason we don't get data from the RWIS stations, we should display it properly. The idea is to colour the road icons in grey and to show in the window detail that the user can open by clicking on the icon the last data record available (with reference timestamp information included!)

**Comment by madeincima** [comment]
I agree, here the color for the icon: #acacac

**Comment by bertolla** [comment]
... and you have to add the symbol in the legend and describe it.

Saving the last valid value is not as simple as it might seem to you. It's quite complicated to implement this on the geoserver side, since we are just working with plain SQL Syntax. We could try to use the html5 offline storage of the browser but i don't know how you expect it to work.

**Comment by ohnewein** [comment]
I don't think this can be implemented with offline HTML5 feature. What Roberto expects is that there is a kind of fallback to the last valid value. This fallback is not per single client, but for all clients the same. Has to be handled on server side.

This idea is the following (pseudo Java code):

public DATA getData() {
   DATA value = getDataFromDB();
   if (value == null) {
      value = getLastValidDataFromDB();
  }
  return value;
}

**Comment by bertolla** [comment]
It can be done in HTML5, by saving it in the offline store, overwriting it as long the value is valid and restoring it, if it's not. 
We have Geoserver as Endpoint, which retrieves  the data off all stations directly from db like this:

`````` SELECT
station_id,station_name,rel_time,rel_temperatura_ambientale,rel_umidita_relativa,rel_velocita_vento,rel_pressione_atmosferica,rel_temperatura_suolo,
case 
when rel_tipo_precipitazione <1 or rel_intensita_precipitazione <1 then 0
when rel_tipo_precipitazione is null or rel_intensita_precipitazione is null then 0
ELSE rel_tipo_precipitazione*10+rel_intensita_precipitazione
END::INT as rel_precipitazione_map,
--12::INT as rel_precipitazione_map,
case 
when val_temperatura_suolo <=2 THEN 0
ELSE 1
END as rel_temperatura_map,
the_geom
FROM

(
SELECT st.id as station_id,
name as station_name,

max(m.timestamp) as rel_time,

max(case m.type_id when 938 then round(m.value::numeric, 1)::text || ' ' || t.cunit end) as rel_temperatura_ambientale,
max(case m.type_id when 939 then m.value::text || ' ' || t.cunit end) as rel_umidita_relativa,
max(case m.type_id when 940 then round(m.value::numeric, 1)::text || ' ' || t.cunit end) as rel_velocita_vento,
max(case m.type_id when 941 then m.value::text || ' ' || t.cunit end) as rel_pressione_atmosferica,
max(case m.type_id when 942 then m.value END) as rel_tipo_precipitazione,
max(case m.type_id when 943 then m.value END) as rel_intensita_precipitazione,
max(case m.type_id when 944 then round(m.value::numeric, 1)::text || ' ' || t.cunit end) as rel_temperatura_suolo,
max(case m.type_id when 944 then round(m.value::numeric, 2) end) as val_temperatura_suolo,
pointprojection as the_geom
from intime.station st
JOIN intime.measurement m ON st.id=m.station_id
JOIN intime.type t ON m.type_id=t.id
where stationtype= 'RWISstation' and  rtype = 'Mean'
group by st.id, name, pointprojection,m.timestamp -- , m.value, t.cunit, 
) as foo
order by station_id```
``````

**Comment by rcavaliere** [comment]
Is it possible to modify this SQL statement in order to return the timestamp of the last data record in the measurement station? In this way, could it be possible to compare this timestamp with the current one, e.g. as it is implemented in BZParking? How does it work there?

**Comment by ohnewein** [comment]
If you do it as HTML5 offline implementation, what happens if the client goes on the web-app for the first time ever and there is no actual data?

**Comment by rcavaliere** [comment]
I am not sure that this functionality is implemented. I wait for a station to be offline to check this.
