### ISSUE TITLE
Smartphone: header

### ISSUE THREAD

**Issue by madeincima** [tis-innovation-park/cleanroads-map#10]
Reduce the blue bar with the languages, make the logo a bit smaller and position the menu icon / beta version correctly as per the image below (left is the current site, right the design).

![img_1631](https://cloud.githubusercontent.com/assets/4242599/11532736/20867382-9906-11e5-9541-9d695a010917.jpg)

**Comment by bertolla** [comment]
Reduced the blue bar and aligned and resized logo

**Comment by rcavaliere** [comment]
I think we are just missing the word "Versione BETA" instead of "BETA". But I would keep it as it is now.
