### ISSUE TITLE
Smartphone: tooltip

### ISSUE THREAD

**Issue by madeincima** [tis-innovation-park/cleanroads-map#11]
Fonts needs to be fixed as per issue #5. Make them smaller to (see the attached image, design to the left, current site to the right). The X icon should be thinner and positioned properly. Values in the tooltip should go on a new line. The shadow is way to strong and should go from to to bottom.

![img_1632](https://cloud.githubusercontent.com/assets/4242599/11532800/9ce3e590-9906-11e5-8fb3-5e74e4620e39.jpg)

**Comment by bertolla** [comment]
I kinda fixed this problem, not by reducing the font but through floating.

Is it just my imagination or is the font a different one?

**Comment by rcavaliere** [comment]
It looks now ok for me. The font seems correct.
