### ISSUE TITLE
Smartphone: legenda

### ISSUE THREAD

**Issue by madeincima** [tis-innovation-park/cleanroads-map#13]
As per the desktop version, make sure you fix all the alignments (i.e. logo and text below). See image below (design on the left, current site on the right).

  ![img_16299](https://cloud.githubusercontent.com/assets/4242599/11532907/34d9dcb0-9907-11e5-9ec4-fd950c17181d.jpg)

**Comment by bertolla** [comment]
Languages and header with logo and menu will be aligned in next release
