### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by madeincima** [tis-innovation-park/cleanroads-map#14]
It'd be better if smartphone styles for tooltips would be triggered based on media queries rather then user agents. If you now resize the window on desktop to a smartphone size, you still get the tooltips for desktop (not displayed in panel).

**Comment by bertolla** [comment]
To do this check in js I would need to use the window.matchMedia function which does not work in ie9 and lower. IE9 is a requisit by the province of Trento. Maybe there is some better solution i don't know off or I can't think off right now

**Comment by rcavaliere** [comment]
If we don't find a technical solution for that I would leave everything as it is. The app is currently very accessed by people in the Province of Trento through old Windows desktop machines. We have already faced visualization issues.
