### ISSUE TITLE
Desktop: Partner & Contribuisci

### ISSUE THREAD

**Issue by madeincima** [tis-innovation-park/cleanroads-map#6]
Partner looks ticker that Contribuisci. They should be the same. See attached image. Left is the current site, right is the original design. Font should be changed too.

![right-panels](https://cloud.githubusercontent.com/assets/4242599/11530897/a7cd41c6-98f8-11e5-8906-f972711c3c3d.jpg)

**Comment by bertolla** [comment]
Small margin issue, fixed in next release
