### ISSUE TITLE
Desktop: Tooltip

### ISSUE THREAD

**Issue by madeincima** [tis-innovation-park/cleanroads-map#7]
Please change fonts here as per issue #5 and fix font-size. Also, "Aggiornato alle.. " should be smaller and left aligned as per the design. The X icon could be a bit smaller.
See image attached. Left shows the original design, right the current site.

![tooltip](https://cloud.githubusercontent.com/assets/4242599/11530958/3f6529a4-98f9-11e5-8838-7d48a663a0e4.jpg)

**Comment by bertolla** [comment]
Fixed for both sides in next release.
