### ISSUE TITLE
Desktop: Contribuisci

### ISSUE THREAD

**Issue by madeincima** [tis-innovation-park/cleanroads-map#8]
The "Contribuisci" panel needs some styling: use font as per #5 for buttons and heading, part of the buttons text should be in black, the white background should have the same height as the green label.
See image attached. Left shows the current site, right the original design. 

![contribuisci](https://cloud.githubusercontent.com/assets/4242599/11531031/f995df80-98f9-11e5-8a43-671286623317.jpg)

**Comment by bertolla** [comment]
This is a known issue which i was not able to solve yet. Work in progress ...
